# Generated by Django 4.1.5 on 2023-01-04 05:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Chinese Name (e.g. 丙酮, 乙腈)', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnglishName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a English Name (e.g. Acetone, Acetonitrile)', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Location (e.g. B205-4°C-Refrigerator, B205-Table1-Lowbox)', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter a First Name (e.g. Chun)', max_length=100)),
                ('last_name', models.CharField(help_text='Enter a Last Name (e.g. Tang)', max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Name in detail (e.g. Acetonitrile-5L-Masspure)', max_length=200)),
                ('specification', models.CharField(blank=True, help_text='Enter a specification (e.g. 1L, 30mg)', max_length=200, null=True)),
                ('cas', models.CharField(blank=True, help_text='Enter a <a href="https://en.wikipedia.org/wiki/CAS_Registry_Number">CAS</a> (e.g. 921-60-8)', max_length=200, null=True)),
                ('purchase_note', models.CharField(blank=True, help_text='Enter a purchase note (e.g. hyperlink, item No.)', max_length=200, null=True)),
                ('note', models.TextField(blank=True, help_text='Enter a brief note', max_length=1000, null=True)),
                ('chinese_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.chinesename')),
                ('english_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.englishname')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Purchase Source (e.g. Aladdin, 源叶生物)', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Tag in English (e.g. Toxic, Avoid Light)', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReagentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('63b5ca0d-052c-40d4-844d-065b2013c19e'), help_text='Unique ID for this particular reagent across whole database, be careful to change!!', primary_key=True, serialize=False)),
                ('register_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('name', models.CharField(blank=True, default='None-20230104', max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('n', 'Never Used'), ('o', 'Occupied'), ('a', 'Available'), ('r', 'Run out')], default='o', help_text='Reagent Status', max_length=1)),
                ('note', models.TextField(blank=True, help_text='Enter a brief note', max_length=1000, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.location')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.principal')),
                ('reagent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.reagent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reagent',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.source'),
        ),
        migrations.AddField(
            model_name='reagent',
            name='tags',
            field=models.ManyToManyField(help_text='Select a tags for this book', to='catalog.tags'),
        ),
    ]
