# Generated by Django 4.1.5 on 2023-01-05 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reagentinstance',
            options={'ordering': ['-register_date', 'name']},
        ),
        migrations.AlterField(
            model_name='reagent',
            name='cas',
            field=models.CharField(blank=True, help_text='Enter a <a href="https://en.wikipedia.org/wiki/CAS_Registry_Number">CAS</a> (e.g. 921-60-8)', max_length=200, null=True, verbose_name='CAS'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='note',
            field=models.CharField(blank=True, help_text='Enter a brief note', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reagentinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular reagent across whole database, be careful to change!!', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reagentinstance',
            name='name',
            field=models.CharField(blank=True, default='610202-20230105', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reagentinstance',
            name='note',
            field=models.CharField(blank=True, help_text='Enter a brief note', max_length=1000, null=True),
        ),
    ]
