# Generated by Django 4.1.5 on 2023-01-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_reagentinstance_options_alter_reagent_cas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentinstance',
            name='name',
            field=models.CharField(blank=True, default='978345-20230105', max_length=200, null=True),
        ),
    ]
